# Site settings
title: 'Tech Blog @Maddyone'
email: info@maddyzone.com
description: > # this means to ignore newlines until "baseurl:"
  Articles on Node.js ,JavaScript, Angular, React and HTML5
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tech-blog.maddyzone.com" # the base hostname & protocol for your site
twitter_username: riturajratan
github_username:  riturajratan
exclude: ['node_modules']
paginate: 10
paginate_path: "/page:num/"
permalink: /:year/:month/:title
sass:
  compressed: true

# Build settings
markdown: kramdown

# Gems
gems: [jekyll-paginate]
